//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GD_LIQUIDACION_2022.WebLogin {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="WebLogin.loginSoap")]
    public interface loginSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user_name del espacio de nombres http://microsoft.com/webservices/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/recibe_datos_usuario", ReplyAction="*")]
        GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioResponse recibe_datos_usuario(GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/recibe_datos_usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioResponse> recibe_datos_usuarioAsync(GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recibe_datos_usuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recibe_datos_usuario", Namespace="http://microsoft.com/webservices/", Order=0)]
        public GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequestBody Body;
        
        public recibe_datos_usuarioRequest() {
        }
        
        public recibe_datos_usuarioRequest(GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class recibe_datos_usuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user_pass;
        
        public recibe_datos_usuarioRequestBody() {
        }
        
        public recibe_datos_usuarioRequestBody(string user_name, string user_pass) {
            this.user_name = user_name;
            this.user_pass = user_pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recibe_datos_usuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recibe_datos_usuarioResponse", Namespace="http://microsoft.com/webservices/", Order=0)]
        public GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioResponseBody Body;
        
        public recibe_datos_usuarioResponse() {
        }
        
        public recibe_datos_usuarioResponse(GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class recibe_datos_usuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recibe_datos_usuarioResult;
        
        public recibe_datos_usuarioResponseBody() {
        }
        
        public recibe_datos_usuarioResponseBody(string recibe_datos_usuarioResult) {
            this.recibe_datos_usuarioResult = recibe_datos_usuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface loginSoapChannel : GD_LIQUIDACION_2022.WebLogin.loginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class loginSoapClient : System.ServiceModel.ClientBase<GD_LIQUIDACION_2022.WebLogin.loginSoap>, GD_LIQUIDACION_2022.WebLogin.loginSoap {
        
        public loginSoapClient() {
        }
        
        public loginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public loginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public loginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public loginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioResponse GD_LIQUIDACION_2022.WebLogin.loginSoap.recibe_datos_usuario(GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequest request) {
            return base.Channel.recibe_datos_usuario(request);
        }
        
        public string recibe_datos_usuario(string user_name, string user_pass) {
            GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequest inValue = new GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequest();
            inValue.Body = new GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequestBody();
            inValue.Body.user_name = user_name;
            inValue.Body.user_pass = user_pass;
            GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioResponse retVal = ((GD_LIQUIDACION_2022.WebLogin.loginSoap)(this)).recibe_datos_usuario(inValue);
            return retVal.Body.recibe_datos_usuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioResponse> GD_LIQUIDACION_2022.WebLogin.loginSoap.recibe_datos_usuarioAsync(GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequest request) {
            return base.Channel.recibe_datos_usuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioResponse> recibe_datos_usuarioAsync(string user_name, string user_pass) {
            GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequest inValue = new GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequest();
            inValue.Body = new GD_LIQUIDACION_2022.WebLogin.recibe_datos_usuarioRequestBody();
            inValue.Body.user_name = user_name;
            inValue.Body.user_pass = user_pass;
            return ((GD_LIQUIDACION_2022.WebLogin.loginSoap)(this)).recibe_datos_usuarioAsync(inValue);
        }
    }
}
